# Site settings
title: Coded Poetry
description: and other technical thoughts...
#baseurl: "/will-jekyll-template" # the subpath of your site, e.g. /blog
url: "http://codedpoetry.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Fernando Llaca
user_description: Full-Stack developer and DevOps engineer. Code and Poetry enthusiast.
user_title: Poetry Developer 
email: ferllarom@gmail.com
twitter_username: NandoLlaca
github_username:  fllaca
gplus_username:  fllaca
linkedin_username: fernando-llaca
disqus_username: fllaca

authors:
  fer:
    name: Fernando Llaca
    description: Full-Stack developer and DevOps engineer. Code and Poetry enthusiast.
    email: ferllarom@gmail.com
    avatar: fer.jpg
    twitter: NandoLlaca
    github: fllaca
  pablo:
    name: Pablo PÃ©rez Luna
    description: Fucking master of the universe
    email: pablopl87@gmail.com
    avatar: pablo.png
    twitter: p_blin
    github: p_blin


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: Easy Links for JIRA
    url: /easy-links-for-jira
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
